### PR TITLE
fix(dex): migration for dex trait proto encodings

### LINKED ISSUE #4340: Chain halt during swap execution on post-upgraded devnet
**Describe the bug**

On a local devnet on which I performed a chain upgrade (this may or may not be relevant), I saw a chain halt while swapping:
```
2024-05-07T03:02:26.618921Z  INFO abci:EndBlock{height=704}: penumbra_app::server::consensus: ending block height=704
thread 'tokio-runtime-worker' panicked at /Users/hdevalence/code/penumbra/penumbra/crates/core/component/dex/src/component/router/fill_route.rs:502:14:
writing to storage should not fail: could not decode proto from bytes

Caused by:
    failed to decode Protobuf message: invalid tag value: 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at /Users/hdevalence/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tower-abci-0.11.1/src/v037/server.rs:179:75:
called `Result::unwrap()` on an `Err` value: ActorHungUp
```

### PR DESCRIPTION
**Pull request by hdevalence**
## Describe your changes

Fixes a chain halt due to changes introduced in #4188.

Previously, aggregate liquidity lookups in non-verifiable storage (i.e. "how much liquidity is available for trading pair `(A, B)`?") were stored as raw big-endian encoded values. In #4188 the DEX state accessors were refactored and part of that was adjusting the accessors for aggregate liquidity lookups to use `nonverifiable_put`/`nonverifiable_get` instead of the `_raw` methods they were using previously.

## Testing

**Manually testing the values were changed appropriately is actually quite difficult currently as `pcli` doesn't support querying values from non-verifiable storage, and returned values need to be parsed correctly into the `Amount` data type.**

- Create a devnet on v0.73.1
- Watch for changes to the aggregate liquidity prefix: `cargo run --release --bin pcli -- query watch --nv-key-regex 'dex/ab/.*'`
- Submit some liquidity positions. Note down the aggregate liquidity data
- Perform migration to this branch: delegate, propose, vote, halt, migrate, restart network
- The chain will halt if the migration doesn't properly change the encoding of the values. The first test is simply to ensure that the chain can run post-migration.
- A further test is to verify that the aggregate liquidity values remain the same post-migration. Query again and compare

## Issue ticket number and link

Closes #4340

### CODE REVIEW

**Comment by conorsch** [comment]
We merged #4339, so this can be rebased on latest main.

**Comment by conorsch** [comment]
Lots of churn on main, including a fix for https://github.com/penumbra-zone/penumbra/issues/4344. Let's keep this rebased. Locally I'll be cross-checking via #4332. Looks like we're within striking distance on a passing migration test end-to-end.

**Comment by hdevalence** [comment]
To clarify my intent with this PR wasn't that it should become a fix, we should throw this code away — I just wanted to share context while writing up the problem for others to pick up.

**Comment by conorsch** [comment]
Fair, we could just as easily open a new PR for the fix commit. But since it's already here, I think "taking over" this PR and using it to close is good enough. Up to @zbuc: if the debugging commit is no longer useful, we can snip it out pronto.

**Comment by zbuc** [comment]
> Fair, we could just as easily open a new PR for the fix commit. But since it's already here, I think "taking over" this PR and using it to close is good enough. Up to @zbuc: if the debugging commit is no longer useful, we can snip it out pronto.

I removed the debug trace statements, I say using this PR and squashing the commits is fine.

**Comment by hdevalence** [comment]
sounds good, just wanted to clarify intent

File: crates/bin/pd/src/migrate/testnet74.rs [hunk 1]
```diff
@@ -37,11 +37,40 @@ async fn fix_arb_execution_outputs(delta: &mut StateDelta<Snapshot>) -> anyhow::
...
+        tracing::info!(
+            key = ?EscapedByteSlice(&key),
+            raw_amount = ?EscapedByteSlice(&raw_amount),
+            ?amount,
+            "updated base liquidity index"
+        );
+    }
+
+    Ok(())
+}
```
Comment (conorsch) [inline crates/bin/pd/src/migrate/testnet74.rs:67]: Is this migration fn idempotent? We've been telling folks our migrations are idempotent, but not sure that's the case for this one. Zooming out, the changes in #4339 definitely aren't idempotent, so not blocking on this.

File: crates/bin/pd/src/migrate/testnet74.rs [hunk 2]
```diff
@@ -117,6 +148,9 @@ pub async fn migrate(
         // Write auction parameters
         write_auction_parameters(&mut delta).await?;
 
+        // Rewrite base liquidity indices as proto-encoded
+        rewrite_base_liquidity_indices(&mut delta).await?;
+
```
Comment (conorsch) [inline crates/bin/pd/src/migrate/testnet74.rs:153]: When we circle back to addressing whether or not we want to enforce that all migrations are idempotent, we can sprinkle in some anyhow::Context usage on these calls. The tracing spans are already quite helpful in debugging what failed in a migration, but more context is never a bad thing IMO.

**Review by conorsch — APPROVED** [review]
After following the test plan, post-migration, I no longer see a chain halt, nor do I see any error messages about invalid tags. Post-migration, I was able to submit and claim several swaps. LGTM.

**Comment by hdevalence** [comment]
I also just tested this on the exact same state that caused the failure previously and confirmed that it worked fine. Great work!

File: crates/bin/pd/src/migrate/testnet74.rs (hunk 1 above)
Comment (zbuc) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: Good catch. No, it is not idempotent. I wasn't aware that was a requirement for migrations; I will follow-up

Comment (erwanor) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: How is this not idempotent? if you run it multiple times you will get the same result, no? why not?

Comment (erwanor) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: is it because the encoding changes? that's completely fine imo

Comment (zbuc) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: > How is this not idempotent? if you run it multiple times you will get the same result, no? why not? 

Looking more closely, I am not sure at the moment. If we attempt to decode protobuf encoded Amount as a BE-encoded Amount it could fail silently and the Amount would change. However, this requires the protobuf byte encoding to be the same length as the big-endian encoding.

Comment (erwanor) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: Honestly not completely sure this is important but we can try to first decode it as a proto amount and return early if it works, and proceed if it correctly returns an error. This way it is resistant to accidental double runs

Comment (zbuc) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: There are some edge cases:

```rust
        let a: Amount = 4951760157141521099596496895u128.into();

        println!("amount 1: {:?}", a);

        let proto_a_bytes: Vec<u8> = penumbra_proto::core::num::v1::Amount::from(a).encode_to_vec();

        let amount = Amount::from_be_bytes(proto_a_bytes.as_slice().try_into()?);

        println!("amount 2: {:?}", amount);
```

```console
amount 1: 4951760157141521099596496895

amount 2: 11963051962064242856133983240072462207
```

so it could _theoretically_ still munge some values and be non-idempotent even if we took that approach if everything aligned and the stored `Amount`s were in a specific range and order.

But I'm also not convinced it's worth trying to fix... migration idempotency seems better to solve at a higher level than within individual functions modifying data if it's a design goal, as there are likely other similar cases that will come up in migration code.

Comment (zbuc) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: Ah there's some Discord discussion about this already: https://discord.com/channels/824484045370818580/1052302055680790568/1228444060113698938

Right now, migrations are not idempotent. This may require publishing the post-upgrade root hash, however that doesn't account for migrations affecting non-verifiable storage.

Comment (hdevalence) [reply crates/bin/pd/src/migrate/testnet74.rs:67]: We should not tell people migrations are idempotent.

The right way to handle idempotency, later, is probably to use the ABCI application version and compare against a version number in the state.
