### PR TITLE
crypto: fixes to TradingPair allocation and division of Amounts

### LINKED ISSUE #2350: check and document all constraints added after out of circuit computation
In our R1CS gadgets the most likely places where constraints could be missing are anywhere we are manually doing out-of-circuit computation and then adding constraints based on the result. Before audit I think we should (1) Double check all these locations and (2) Ensure that documentation is added inline in the form of comments (similar to [here](https://github.com/penumbra-zone/penumbra/blob/208e94116d16df376b001b08f47d5ce38b95250a/crypto/src/asset/amount.rs#L86)).

These are the places we need to check: 

## decaf377

- [x] Square roots: https://github.com/penumbra-zone/decaf377/blob/main/src/r1cs/fqvar_ext.rs#L35 - addressed by https://github.com/penumbra-zone/decaf377/pull/52

## penumbra-crypto

- [x] Amount division: https://github.com/penumbra-zone/penumbra/blob/main/crypto/src/asset/amount.rs#L55
- [x] Applying a `Penalty`: https://github.com/penumbra-zone/penumbra/blob/main/crypto/src/stake/penalty.rs#L102
- [x] Constrain a < b for `TradingPair` 

## TCT

- [x] Computing `WhichWay` is done out of circuit and then witnessed in circuit: https://github.com/penumbra-zone/penumbra/blob/main/tct/src/r1cs.rs#L146 (note that doing this in circuit I think would solve #2135 but doing the computation involves [bit ops](https://github.com/penumbra-zone/penumbra/blob/208e94116d16df376b001b08f47d5ce38b95250a/tct/src/internal/path.rs#L87) which is why I did it this in this way)  - resolved by #2533
- [x] Adding variables for the epoch, block, and commitment index from position: https://github.com/penumbra-zone/penumbra/blob/main/tct/src/r1cs.rs#L32 - I think we need to add additional constraints here based on the position var - resolved by #2533

### PR DESCRIPTION
**Pull request by redshiftzero**
Closes #2350

This PR:
- Reworks the allocation of `TradingPairVar` (represents a `TradingPair` in R1CS), to note that we are intentionally not checking that the asset IDs are ordered as expected in the canonical representation of the out of circuit `TradingPair`. This is because we are only using the `TradingPair`'s two asset IDs in the swap commitment integrity check, which will fail if the asset IDs are switched.
- Fixes two issues with the R1CS implementation of Euclidean division of `AmountVar`s, where we now ensure that the remainder cannot equal the divisor, and that the divisor is non-zero. 
- Adds tests for all circuits to ensure that the parameters and circuits are in sync, i.e. that a circuit-breaking change has not unintentionally been made.

### CODE REVIEW

File: crypto/src/dex/trading_pair.rs [hunk 1]
```diff
@@ -121,6 +123,40 @@ impl TryFrom<[u8; 64]> for TradingPair {
...
+        let ns = cs.into();
+        let cs = ns.cs();
+        let trading_pair = f()?.borrow().clone();
+        let asset_1 = AssetIdVar::new_variable(cs.clone(), || Ok(trading_pair.asset_1()), mode)?;
+        let asset_2 = AssetIdVar::new_variable(cs, || Ok(trading_pair.asset_2()), mode)?;
+        // A valid `TradingPair` has a canonical ordering.
+        // Constrain: asset_1 <= asset_2.
+        asset_1
+            .asset_id
+            .enforce_cmp(&asset_2.asset_id, core::cmp::Ordering::Less, true)?;
```
Comment (redshiftzero) [inline crypto/src/dex/trading_pair.rs:147]: I think this doesn't work because `enforce_cmp` [expects](https://docs.rs/ark-r1cs-std/latest/ark_r1cs_std/fields/fp/enum.FpVar.html#method.enforce_cmp) the variables to be `<= (p - 1)/2` in size. The other places where we use the `enforce_cmp` method should be checked too.
