### PR TITLE
fix: Include fee in PEN in transaction value balance

### LINKED ISSUE #170: crypto: fix fee handling in transaction builder
Currently in the transaction builder we track the value balance and error if it is non-zero (meaning value is being created or destroyed, not just moved around): https://github.com/penumbra-zone/penumbra/blob/main/crypto/src/transaction/builder.rs#L29

We should edit the `set_fee` method to include the fee in the value balance computation: https://github.com/penumbra-zone/penumbra/blob/main/crypto/src/transaction/builder.rs#L130

For now the fee must be in set in `PEN`.

### PR DESCRIPTION
**Pull request by redshiftzero**
This includes the fee in the transaction builder's value balance computation

Closes #170

### CODE REVIEW

File: crypto/src/transaction/builder.rs [hunk 1]
```diff
@@ -126,7 +126,24 @@ impl Builder {
     }
 
     /// Set the transaction fee in PEN.
-    pub fn set_fee(mut self, fee: u64) -> Self {
+    pub fn set_fee<R: RngCore + CryptoRng>(mut self, rng: &mut R, fee: u64) -> Self {
+        let pen_trace = b"PEN";
```
Comment (redshiftzero) [inline crypto/src/transaction/builder.rs:130]: Did we want to standardize on `pen` or `PEN`?

Comment (hdevalence) [reply crypto/src/transaction/builder.rs:130]: let's use lower case in the code, and figure out a final name later

File: crypto/src/transaction/builder.rs [hunk 2]
```diff
@@ -126,7 +126,24 @@ impl Builder {
     }
 
     /// Set the transaction fee in PEN.
-    pub fn set_fee(mut self, fee: u64) -> Self {
+    pub fn set_fee<R: RngCore + CryptoRng>(mut self, rng: &mut R, fee: u64) -> Self {
```
Comment (hdevalence) [inline crypto/src/transaction/builder.rs:129]: this could be rng: mut R instead, and then people can pass an owned or boorowed RNG (since &mut R impls RngCore if R does).

**Review by hdevalence — APPROVED** [review]
LGTM mod (tioli) comments

**Comment by redshiftzero** [comment]
this has the wrong sign: 55cecbeb754e2ec169c4986730594b0663ca7c2c fixes
