### PR TITLE
Implement a minimal fix for Penalty calculation in UndelegateClaimCircuit

### LINKED ISSUE #3456: staking: update `UndelegateClaimCircuit` to use `penumbra-num` amount and fixpoint arithmetic
@erwanor is taking a first pass at updating the penalty calculation in the staking component to use the `U128x128` fixpoint type and amounts throughout (ref #3453).

Next the `UndelegateClaimCircuit` will also need to be updated since it uses the penalty calculation (as in `Penalty::apply_to`). If the penalty representation changes from a u64 to a `U128x128` or amount, then the R1CS `PenaltyVar` representation will need to be updated accordingly. We then will need to update the constraints that assert that the `penalized_amount` - currently represented as an `AmountVar` and constrained to be 128 bits - has been computed correctly based on the penalty and amount being unbonded. The other parts of the circuit will be unchanged. 

Then we will determine if the circuit cost exceeds the size of the phase 1 output for the `UndelegateClaimCircuit`. If it exceeds the size of the phase 1 output which was the existing circuit size rounded up to the nearest power of 2 (we can add 1608 constraints), then we will either optimize the circuit cost to fit or specialize a phase 1 output of another circuit to this end (h/t to @cronokirby for this suggestion).

### PR DESCRIPTION
**Pull request by cronokirby**
Closes #3456.

I lost track of what exactly had changed in https://github.com/penumbra-zone/penumbra/pull/3466, so I instead just implemented this without basing myself off of that PR.

The difference in approach is that this PR makes the `Penalty` type completely opaque, and modifies no other typed values in the system to use Penalty or U128x128 except the internal representation of the Penalty type.

I think making Penalty opaque is the correct approach, because it makes it impossible for there to ever be any confusion about what the meaning of the u64s you're passing in to Penalty are.

Another difference with the other PR is that the circuit behavior should match the out of circuit behavior exactly now, whereas the other PR is missing a 1 - X operation in the circuit. This bumps up the constraint count to 15714. (We can golf this down with at least two strategies, but we don't really need to, it still fits).

One *important* thing that should be considered is the fact that this PR modifies the proto-encoding of penalty to now hold the full precision of U128x128 by encoding the 32 bytes that value consists of. I'm not quite sure of the ramifications of this change but it should be considered.

Update (2023-12-06T08:52:27+00:00): I've switched the Penalty to store the a fraction from [0, 1], representing the *kept* amount, rather than the removed amount. This simplifies compounding and the circuit, and also fixes the weird test failures I tried to debug for a couple hours.

### CODE REVIEW

**Comment by redshiftzero** [comment]
Per discussion in today's sprint planning meeting, I'll add a commit later today that adds a test of the `U128x128Var::round_down_to_amount` functionality

File: crates/core/component/stake/src/penalty.rs [hunk 1]
```diff
@@ -99,80 +132,17 @@ impl AllocVar<Penalty, Fq> for PenaltyVar {
...
-
-impl From<&PenaltyVar> for AmountVar {
-    fn from(penalty_var: &PenaltyVar) -> Self {
-        // `AmountVar`s must fit in 128 bits, but `PenaltyVar`s have already
-        // been constrained to fit in 64 bits, so we can safely
-        // construct an `AmountVar` from a `PenaltyVar`.
-        AmountVar {
-            amount: penalty_var.inner.clone(),
-        }
+        Ok(Self {
```
Comment (redshiftzero) [inline crates/core/component/stake/src/penalty.rs:135]: Here in `AllocVar` as an additional guard we could return an error if `mode` is not `AllocationMode::Input`

**Review by redshiftzero — APPROVED** [review]

File: crates/core/component/stake/src/penalty.rs [hunk 2]
```diff
@@ -12,52 +10,66 @@ use penumbra_asset::{
...
 };
-use penumbra_num::{fixpoint::bit_constrain, Amount, AmountVar};
+use penumbra_num::{
+    fixpoint::{U128x128, U128x128Var},
+    Amount, AmountVar,
+};
 
 /// Tracks slashing penalties applied to a validator in some epoch.
 ///
 /// The penalty is represented as a fixed-point integer in bps^2 (denominator 10^8).
```
Comment (erwanor) [inline crates/core/component/stake/src/penalty.rs:20]: We should replace this description

Comment (erwanor) [reply crates/core/component/stake/src/penalty.rs:20]: We can remove all mention of how it is represented internally since the type is opaque

File: crates/core/component/stake/src/penalty.rs [hunk 3]
```diff
@@ -12,52 +10,66 @@ use penumbra_asset::{
...
-        )
-        .expect("all u64 values should be valid Amounts")
+    pub fn apply_to_amount(&self, amount: Amount) -> Amount {
+        self.apply_to(amount)
+            .round_down()
+            .try_into()
+            .expect("converting integral U128xU128 into Amount will succeed")
+    }
+
+    /// Apply this `Penalty` to an some fracton.
```
Comment (erwanor) [inline crates/core/component/stake/src/penalty.rs:70]: nit: typos

**Review by hdevalence — APPROVED** [review]
This LGTM. Let's land this prior to the Testnet 64 release, and do another round of circuit assurance during Testnet 64.
