### PR TITLE
feat: add `DisplayDenom` formatting and parsing, fix display parsing bug

### LINKED ISSUE #292: Implement value parsing methods on `DisplayDenom`
In #283 we created `BaseDenom` and `DisplayDenom` types. We'd like to be able to accept and display values in the display denominations as well as the base denomination.

Currently, all of our internal numerical representations are always integral values in the base denomination, preventing accidentally mixing units.  This seems like a useful property to maintain, which suggests using only formatted string representations for the display denomination values.

To do this, we should add two methods:
```rust
impl DisplayDenom {
    pub fn format_value(&self, value: u64) -> String {
        // e.g., with exponent 6, 1782000 formats to 1.782
   }
   pub fn parse_value(&self, value: &str) -> Result<u64, Error> {
        // e.g., with exponent 6, 1.782 parses as 1782000
        // and 1.7820001 errors (cannot be represented exactly)
   }
}
```
and remove the existing `exponent` (not needed once this exists) and `raw_name` (provided by `Display`) methods.

Both formatting and parsing should be done using exact arithmetic, for instance (sketch):

* To format, compute the quotient and remainder `v = v1 * 10^e + v2`, then format as `format!("{}.{}", v1, v2)`;
* To parse, split the input at `.` into `left` and `right` (with `right` possibly empty), parse `left` and `right` as integers `v1` and `v2`, multiply `v2` by `10^(e - right.len())` (effectively padding with 0s on the right, erroring if `right.len() > e` to detect values that can't be represented exactly), and then compute `v = v1 * 10^e + v2`.

The computations during parsing should probably be done with checked arithmetic to detect overflows.

### PR DESCRIPTION
**Pull request by redshiftzero**
Closes #292, now working on adding property test

### CODE REVIEW

File: crypto/src/asset/registry.rs [hunk 1]
```diff
@@ -82,24 +82,36 @@ impl Registry {
...
+        if self.parse_base(raw_denom).is_some() {
+            let base_inner = self.parse_base(raw_denom).unwrap().inner;
+
+            // The display version of the base denomination is always the last in the
+            // `units`.
+            let unit_index = base_inner.units.len() - 1;
+            return Some(DisplayDenom {
+                inner: base_inner,
+                unit_index,
+            });
```
Comment (hdevalence) [inline crypto/src/asset/registry.rs:94]: I think this code could be simpler, by doing something like
```
if let Some(base_denom) = self.parse_base(raw_denom) {
    return Some(base_denom.units().last().expect("base denom always has at least one display denom"));
}
```
since the current code is constructing the whole base denomination twice and then re-constructing the display denom that's already present in it.

File: crypto/src/asset.rs [hunk 2]
```diff
@@ -42,11 +46,66 @@ mod tests {
...
+        assert_eq!(
+            penumbra_display_denom.parse_value("1.782").unwrap(),
+            1782000
+        );
+
+        let mpenumbra_display_denom = REGISTRY.parse_display("mpenumbra").unwrap();
+        assert_eq!(
+            mpenumbra_display_denom.parse_value("1782").unwrap(),
+            1782000
+        );
```
Comment (hdevalence) [inline crypto/src/asset.rs:78]: Could be nice to check that
```
mpenumbra_display_denom.parse_value("1782.0001").is_err()
```
just to exercise the too-much-precision codepath.

**Review by hdevalence — APPROVED** [review]
LGTM mod comments!

File: crypto/src/asset/registry.rs (hunk 1 above)
Comment (redshiftzero) [reply crypto/src/asset/registry.rs]: thanks! this is simpler, updated
