### PR TITLE
pcli: use a default timeout height for ibc withdrawals

### LINKED ISSUE #3206: pcli: timeout height for ibc transfers should have default value
The command `pcli tx withdraw` takes a `--timeout-height`, which is difficult for users to specify accurately. The "default" value is currently `0-0`, but this will never work, always yielding the error: `error: Invalid value "0-0" for '--timeout-height <TIMEOUT_HEIGHT>': attempted to parse an invalid zero height`.

The structure of that arg is a tuple of:

1. revision number on counterparty chain id (e.g., `osmo-test-5` -> `5`)
2. block height on counterparty chain

In order to provide a sane default value, given that we already require the user to specify a `--channel-id`, we can use that information to look up IBC client information, and infer the revision number from the last recorded height for the client. The height that the client stores in is in IBC format, meaning the revision number and block height are already specified, meaning we don't need a separate lookup.

Finally, inspired by the `rly` tool, let's change the flag from `--timeout-height` to `--timeout-height-offset`, so that expiry happens _n_ blocks in the future. As for a sane value for this, how about 1000.

### PR DESCRIPTION
**Pull request by avahowell**
Closes #3206 . Won't work until we have implemented the remaining IBC queries (currently all the channel ones are missing)

### CODE REVIEW

**Comment by conorsch** [comment]
> Won't work until we have implemented the remaining IBC queries (currently all the channel ones are missing)

Added in https://github.com/penumbra-zone/penumbra/pull/3572

File: crates/bin/pcli/src/command/tx.rs [hunk 1]
```diff
@@ -858,13 +867,72 @@ impl TxCmd {
...
+                    None => {
+                        // look up the height for the counterparty and add 2 days of block time
+                        // (assuming 10 seconds per block) to it
+
+                        // look up the client state from the channel by looking up channel id -> connection id -> client state
+                        let mut ibc_channel_client =
+                            IbcChannelQueryClient::new(app.pd_channel().await?);
+
+                        let req = QueryChannelRequest {
+                            port_id: "transfer".to_string(),
```
Comment (conorsch) [inline crates/bin/pcli/src/command/tx.rs:881]: Side note: we hardcode `"transfer"` a lot of places, when referring to the IBC port. Should we not constify that value in the IBC crate somewhere, so we can tersely refer to it as the constant value it is?

File: crates/bin/pcli/src/command/tx.rs [hunk 2]
```diff
@@ -858,13 +867,72 @@ impl TxCmd {
                     .full_viewing_key
                     .ephemeral_address(OsRng, AddressIndex::from(*source));
 
+                let timeout_height = match timeout_height {
+                    Some(h) => h.clone(),
+                    None => {
+                        // look up the height for the counterparty and add 2 days of block time
+                        // (assuming 10 seconds per block) to it
```
Comment (conorsch) [inline crates/bin/pcli/src/command/tx.rs:874]: Why assume 10s per block? Looking at the current Testnet 64, it looks like blocks actually take about 5s:

block-times

which I assume is coming from the cometbft value we set here: https://github.com/penumbra-zone/penumbra/blob/v0.64.1/testnets/cometbft_config_template.toml#L413

File: crates/bin/pcli/src/command/tx.rs [hunk 3]
```diff
@@ -858,13 +867,72 @@ impl TxCmd {
...
+                            .client_state
+                            .ok_or_else(|| anyhow::anyhow!("client state not found"))?;
+
+                        let tm_client_state = TendermintClientState::try_from(client_state)?;
+
+                        let last_update_height = tm_client_state.latest_height;
+
+                        IbcHeight {
+                            revision_number: last_update_height.revision_number,
+                            revision_height: last_update_height.revision_height + 87400,
```
Comment (conorsch) [inline crates/bin/pcli/src/command/tx.rs:925]: Related to question above: where does `87400` come from? `24 * 60 * 60 = 86400` but the comment at the top of the match suggests it should be _two_ days, not one. Can we var this value and explain its construction in a comment?

**Review by conorsch — COMMENTED** [review]
Requesting some clarification to aid my own understanding of the diff.

File: crates/bin/pcli/src/command/tx.rs (hunk 2 above)
Comment (hdevalence) [reply crates/bin/pcli/src/command/tx.rs:874]: The number applies to counterparty chains, so we can't get it correct, since they all have different values, it'll just be an approximation. See 

https://twitter.com/larry0x/status/1742764484144320997/photo/1

all the cosmos chains have different block times

Comment (conorsch) [reply crates/bin/pcli/src/command/tx.rs:874]: Ahh, of course. That makes a lot more sense!

File: crates/bin/pcli/src/command/tx.rs (hunk 1 above)
Comment (avahowell) [reply crates/bin/pcli/src/command/tx.rs:881]: We do this, it's `Portid::transfer()` in ibc-types. i'll update this pr to use that

File: crates/bin/pcli/src/command/tx.rs (hunk 3 above)
Comment (avahowell) [reply crates/bin/pcli/src/command/tx.rs:925]: it should be ((24*60*60)/10) * 2, since we're assuming 10s per block

**Comment by avahowell** [comment]
Updated with review comments

**Comment by conorsch** [comment]
Awesome, thanks for explaining, @avahowell!
