### PR TITLE
Retrieve SwapExecutions from nonverifiable storage in RPC

### LINKED ISSUE #4618: Dex SwapExecutions endpoint returning no data
**Describe the bug**
The dex swap executions function on the query service returns no data.

**To Reproduce**
```
grpcurl -plaintext -d '{"start_height": 0, "end_height": 546450 }'     127.0.0.1:8081 penumbra.core.component.dex.v1.QueryService/SwapExecutions
```

**Expected behavior**
A list of swaps with traces

**Screenshots**
n/a

**Additional context**
Relevant function https://buf.build/penumbra-zone/penumbra/docs/main:penumbra.core.component.dex.v1#penumbra.core.component.dex.v1.SwapExecution

### PR DESCRIPTION
**Pull request by zbuc**
## Describe your changes

The `SwapExecutions` RPC was retrieving results from the JMT, but historic `SwapExecution`s are actually stored in nonverifiable storage.

## Issue ticket number and link

Closes #4618 

## Checklist before requesting a review

- [x] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > Only changes RPC response

### CODE REVIEW

File: crates/core/component/dex/src/component/rpc.rs [hunk 1]
```diff
@@ -309,9 +309,9 @@ impl QueryService for Server {
         let trading_pair: Option<DirectedTradingPair> =
             trading_pair.map(|trading_pair| trading_pair.try_into().expect("invalid trading pair"));
 
-        let s = state.prefix(state_key::swap_executions());
+        let s = state.nonverifiable_prefix(&state_key::swap_executions().as_bytes());
```
Comment (erwanor) [inline crates/core/component/dex/src/component/rpc.rs:312]: I think we could use a range query too and avoid iterating over every key.

**Review by erwanor — APPROVED** [review]
LGTM
