### PR TITLE
fix: use swap claim address for transaction summary

### LINKED ISSUE #5200: LQT: pcli cannot list-tx-hashes
**Describe the bug**
While testing on the LQT branch (#5010) I recently encountered `pcli` failing to display transaction hashes. 

**To Reproduce**
1. Make sure you've voted in the testnet LQT, via Prax.
2. Check out the `protocol/lqt_branch`
3. Run `cargo run --release --bin pcli -- view balance` and confirm successful sync
4. Run `cargo run --release --bin pcli -- view list-tx-hashes` and observe error

**Expected behavior**
I expected to see a list of historical transaction hashes, including my votes.

**Screenshots**
```
❯ cargo run --release --bin pcli -- view list-tx-hashes
    Finished `release` profile [optimized] target(s) in 0.43s
     Running `target/release/pcli view list-tx-hashes`
2025-05-19T16:18:38.084757Z  INFO pcli::opt: using software KMS custody service
2025-05-19T16:18:38.084787Z  INFO pcli::opt: using local view service path=/home/conor/.local/share/pcli/pcli-view.sqlite
2025-05-19T16:18:38.629274Z  INFO view: penumbra_sdk_view::worker: starting client sync
Scanning blocks from last sync height 572267 to latest height 572267
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
thread 'main' panicked at crates/core/transaction/src/view.rs:165:55:
sender address
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Additional context**
I'm not sure I've ever run `list-tx-hashes` successfully on LQT testnet; I suspect it's LQT votes that are creating the problem but haven't confirmed.

### PR DESCRIPTION
**Pull request by cronokirby**
Using only the outputs runs into some niche issues for certain transactions, this method always works.

## Issue ticket number and link

Closes #5200.

Now, `pcli v list-tx-hashes` should not error out again.

## Checklist before requesting a review

- [x] I have added guiding text to explain how a reviewer should test these changes.

- [x] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > client only

### CODE REVIEW

**Comment by conorsch** [comment]
Nice, will test this against the testnet with a quick local cherry-pick...

**Comment by conorsch** [comment]
Apparently the `list-tx-hashes` was also failing on a mainnet wallet for me; this patch resolves the problem on both branches.

**Comment by cronokirby** [comment]
> Apparently the `list-tx-hashes` was also failing on a mainnet wallet for me; this patch resolves the problem on both branches.

Ok, confirms my assessment that this was just an outstanding bug in the original implementation, unrelated to LQT.

File: crates/core/transaction/src/view.rs [hunk 1]
```diff
@@ -884,6 +884,6 @@ mod test {
 
         let transaction_summary = TransactionView::summary(&transaction_view);
 
-        assert_eq!(transaction_summary.effects.len(), 2);
+        assert_eq!(transaction_summary.effects.len(), 3);
```
Comment (cronokirby) [inline crates/core/transaction/src/view.rs:887]: After inspecting the test, this seems to be correct

**Review by conorsch — APPROVED** [review]
