### PR TITLE
ibc: remediate remaining monorepo issues from zellic audit

### LINKED ISSUE #4546: ibc: Zero out custom fields on client update
**Describe the bug**
When a client upgrade is performed, the verify_client_upgrade_proof function is called to ensure the counterparty has committed the new client state. The corresponding check in ibc-go (https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/upgrade.go#L74) used a zeroed-out client state to verify the proof. It also uses the zeroed-out client state when committing the new client state (https://github.com/cosmos/ibc-go/blob/2555a7c504a904064d659e4c1a3a74000887f73d/modules/core/02-client/keeper/keeper.go#L552-L564).

If the counterparty performing the update is using the ibc-go implementation, Penumbra will fail to verify the client upgrade proof as it will be different to the zeroed-out client state used by ibc-go, resulting in a failed upgrade.

**Expected behavior**
All customizable fields in the client state should be zeroed out before verifying the client upgrade proof, as done in ibc-go.

### LINKED ISSUE #4549: ibc: Frozen client height mismatches with ibc-go spec
**Describe the bug**
Clients that are frozen are always frozen at a specific height. This height has a revision number of 0 and a revision height of 1. This can be seen in the IBC specifications [here](https://github.com/cosmos/ibc/blob/33d936aeecd649f25d4e357c942fcb5e4dec96e3/spec/client/ics-007-tendermint-client/README.md?plain=1#L329) and in ibc-go [here](https://github.com/cosmos/ibc-go/blob/3fbd2dfb5e42dc1cc2c8bb7bb0ff654f13874760/modules/light-clients/07-tendermint/misbehaviour.go#L19).

Penumbra instead uses the current Tendermint block header's height as the frozen height, as seen [here](https://github.com/penumbra-zone/penumbra/blob/c462e9a6cc86a37d42a9d75f1ab9ceb0e3789f77/crates/core/component/ibc/src/component/client.rs#L50).

**Expected behavior**
This likely does not have any security impact, but it is a deviation from the specification and can potentially lead to an issue in the future.

Use a revision number of 0 and height of 1 instead of the current Tendermint block header's height for frozen clients.

### LINKED ISSUE #4550: ibc: Revision number not in state
**Describe the bug**
In ibc-go, the revision number parsed from the chain ID as part of the processed height is stored at "consensusStates/{height}/processedHeight"; in contrast, penumbra- ibc hardcodes a 0 revision number in the processed height and stores it at "ibc/- clients/{client_id}/processedHeights/{height}".

The [GetHeight function](https://github.com/cosmos/ibc-go/blob/3fbd2dfb5e42dc1cc2c8bb7bb0ff654f13874760/modules/light-clients/07-tendermint/header.go#L35-L38) in ibc-go parses the revision number from the chain ID.

The [UpdateState function](https://github.com/cosmos/ibc-go/blob/3fbd2dfb5e42dc1cc2c8bb7bb0ff654f13874760/modules/light-clients/07-tendermint/update.go#L162) calls setConsensusMetadata, which writes to "consensusStates/{height}/processedHeight".

The [put_verified_consensus_state function](https://github.com/penumbra-zone/penumbra/blob/c462e9a6cc86a37d42a9d75f1ab9ceb0e3789f77/crates/core/component/ibc/src/component/client.rs#L132) uses a hardcoded 0 revision number in the stored processedHeight.

**Expected behavior**
This likely does not have any security impact, but it is a deviation from the specification and can potentially lead to an issue in the future.

We should make the heights and paths used for put_verified_consensus_state consistent with setConsensusMetadata.

### LINKED ISSUE #4552: ibc: Trailing hex digits in chain IDs may be treated as revisions
**Describe the bug**
If preserve_chain_id is false when running `pd testnet generate`, theg enerated testnet will have a name ending in 8 hex nybbles, which can be parsed as a decimal approximately 2.3% of the time, which may be interpreted as a revision.

This is the [pd executable](https://github.com/penumbra-zone/penumbra/blob/c462e9a6cc86a37d42a9d75f1ab9ceb0e3789f77/crates/bin/pd/src/main.rs#L426-L429)s generation of hex testnet names.

**Expected behavior**
This likely does not have any security impact, but it is a deviation from the specification and can potentially lead to an issue in the future.

We should either append a -0 to the chain ID or encode the random value as decimal (so that it is consistently treated like a revision).

### LINKED ISSUE #4553: ibc: Mismatch in upper bound for TrustThreshold
**Describe the bug**
Tendermint's TrustThresholdFraction::new enforces that a trust threshold is in the interval [1/3, 1].

Also, TrustThresholdFraction::new is called from ibc-types's ClientState::new, which shares most of its checks with ibc-go's ClientState.Validate, and the corresponding check there is to cometbft's light.ValidateTrustLevel, which also uses the interval [1/3 , 1].

Moreover, penumbra-ibc contains an additional check, validate_trust_threshold, which enforces that the trust threshold used when validating the counterparty's representation of Penumbra's state is in ConnectionOpenTry and ConnectionOpenAck is in the interval [1/3,1) (i.e., strictly less than one), which is more restrictive. The corresponding check in ibc- go's ConsensusHost.ValidateSelfClient uses the same light.ValidateTrustLevel as ClientState.Validate.

The TrustThresholdFraction::new function's enforcement of the interval:

https://github.com/informalsystems/tendermint-rs/blob/c45f593e06eb404259bdd14c4d90c62f73943381/tendermint/src/trust_threshold.rs#L53-L67

The cometbft library's enforcement of the interval:

https://github.com/cometbft/cometbft/blob/fe45483be36ebfea7e172a3ad949e8fe09a8fd95/light/verifier.go#L197-L204

This is the validate_trust_threshold function's enforcement of the interval:

https://github.com/penumbra-zone/penumbra/blob/c462e9a6cc86a37d42a9d75f1ab9ceb0e3789f77/crates/core/component/ibc/src/component/ics02_validation.rs#L146-L160

The ibc-go library uses cometbft's ValidateTrustLevel in ValidateSelfClient:

https://github.com/cosmos/ibc-go/blob/b4651560ec3f363aa705424397b1e164c5594a1e/modules/light-clients/07-tendermint/consensus_host.go#L105-L107

**Expected behavior**
If a penumbra-ibc node were configured to use a trust threshold of 1 (which is technically valid, but has liveness issues and may not provide additional security over a threshold of 23 ), it would incorrectly not be able to open ICS-003 connections, since it would fail to recognize its own state on the counterparty's chain.

The validate_trust_threshold function should permit a trust_threshold of 1:

```
- if trust_threshold.numerator() >= trust_threshold.denominator() {
  + if trust_threshold.numerator() > trust_threshold.denominator() {
```

### PR DESCRIPTION
**Pull request by avahowell**
Closes #4549
Closes #4552
Closes #4553 
Closes #4550 
Closes #4546

### CODE REVIEW

File: crates/core/component/governance/src/component/view.rs [hunk 1]
```diff
@@ -903,9 +903,12 @@ pub trait StateWriteExt: StateWrite + penumbra_ibc::component::ConnectionStateWr
                 let client_id = &ClientId::from_str(client_id)
                     .map_err(|e| tonic::Status::aborted(format!("invalid client id: {e}")))?;
                 let client_state = self.get_client_state(client_id).await?;
-                let client_height = client_state.latest_height();
 
-                let frozen_client = client_state.with_frozen_height(client_height);
+                let frozen_client =
+                    client_state.with_frozen_height(ibc_types::core::client::Height {
+                        revision_number: 0,
+                        revision_height: 1,
```
Comment (erwanor) [inline crates/core/component/governance/src/component/view.rs:910]: ACK.

File: crates/core/component/ibc/src/component/client.rs [hunk 2]
```diff
@@ -79,7 +79,10 @@ pub(crate) trait Ics2ClientExt: StateWrite {
                     trusted_client_state
                         .with_header(verified_header.clone())
                         .expect("able to add header to client state")
-                        .with_frozen_height(verified_header.height()),
+                        .with_frozen_height(ibc_types::core::client::Height {
+                            revision_number: 0,
+                            revision_height: 1,
```
Comment (erwanor) [inline crates/core/component/ibc/src/component/client.rs:84]: ACK.

File: crates/core/component/ibc/src/component/client.rs [hunk 3]
```diff
@@ -106,7 +109,10 @@ pub(crate) trait Ics2ClientExt: StateWrite {
...
```
Comment (erwanor) [inline crates/core/component/ibc/src/component/client.rs:114]: ACK.

File: crates/core/component/ibc/src/component/client.rs [hunk 4]
```diff
@@ -119,7 +125,10 @@ pub(crate) trait Ics2ClientExt: StateWrite {
...
```
Comment (erwanor) [inline crates/core/component/ibc/src/component/client.rs:130]: ACK.

File: crates/core/component/ibc/src/component/client.rs [hunk 5]
```diff
@@ -161,7 +171,7 @@ pub trait ConsensusStateWriteExt: StateWrite + Sized {
 
         self.put(
             state_key::client_processed_heights(&client_id, &height),
-            ibc_types::core::client::Height::new(0, current_height)?,
+            ibc_types::core::client::Height::new(revision_number, current_height)?,
```
Comment (erwanor) [inline crates/core/component/ibc/src/component/client.rs:174]: ACK.

File: crates/core/component/ibc/src/component/ics02_validation.rs [hunk 6]
```diff
@@ -152,8 +152,8 @@ fn validate_trust_threshold(trust_threshold: TrustThreshold) -> anyhow::Result<(
         anyhow::bail!("trust threshold must be greater than 1/3");
     }
 
-    if trust_threshold.numerator() >= trust_threshold.denominator() {
-        anyhow::bail!("trust threshold must be strictly less than 1");
+    if trust_threshold.numerator() > trust_threshold.denominator() {
+        anyhow::bail!("trust threshold must be less than or equal to 1");
```
Comment (erwanor) [inline crates/core/component/ibc/src/component/ics02_validation.rs:156]: ACK.

File: crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs [hunk 7]
```diff
@@ -42,10 +44,34 @@ impl MsgHandler for MsgUpgradeClient {
...
+        // we're going to reset some of the upgraded client state fields to their default values before verifying
+        // the remote's inclusion of the client state; this is what ibc-go does.
+        //
+        // note that later on in this function, we only allow the fields that we didn't reset here to change across upgrades.
+        // this means that there's no danger of a relayer sending an updated state
+        // with a new trust level and lying to us here, causing us to reconfigure the client with a bogus trust level.
+        //
+        // relevant ibc-go code:
+        // https://github.com/cosmos/ibc-go/blob/main/modules/light-clients/07-tendermint/upgrade.go#L74
+        // https://github.com/cosmos/ibc-go/blob/2555a7c504a904064d659e4c1a3a74000887f73d/modules/core/02-client/keeper/keeper.go#L552-L564
```
Comment (erwanor) [inline crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs:62]: Interesting. I realize we haven't tested counterparty host chain upgrade ever, maybe we should do that.

File: crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs [hunk 8]
```diff
@@ -42,10 +44,34 @@ impl MsgHandler for MsgUpgradeClient {
...
+        upgraded_client_state_tm_zeroed_fields.trusting_period = ZERO_DURATION;
+        upgraded_client_state_tm_zeroed_fields.trust_level = TrustThreshold::ZERO;
+        upgraded_client_state_tm_zeroed_fields
+            .allow_update
+            .after_expiry = false;
+        upgraded_client_state_tm_zeroed_fields
+            .allow_update
+            .after_misbehaviour = false;
+        upgraded_client_state_tm_zeroed_fields.frozen_height = None;
+        upgraded_client_state_tm_zeroed_fields.max_clock_drift = ZERO_DURATION;
```
Comment (erwanor) [inline crates/core/component/ibc/src/component/msg_handler/upgrade_client.rs:73]: ACK, all custom fields are reset.

**Review by erwanor — APPROVED** [review]
LGTM

File: crates/bin/pd/src/main.rs [hunk 9]
```diff
@@ -328,7 +328,7 @@ async fn main() -> anyhow::Result<()> {
                     let randomizer = OsRng.gen::<u32>();
                     let chain_id =
                         chain_id.unwrap_or_else(|| env!("PD_LATEST_TESTNET_NAME").to_string());
-                    format!("{}-{}", chain_id, hex::encode(randomizer.to_le_bytes()))
+                    format!("{}-{}", chain_id, randomizer)
```
Comment (conorsch) [inline crates/bin/pd/src/main.rs:331]: N.B. this will update preview/devnet chain ids to a format like `penumbra-testnet-deimos-8-722430144`, where the lattermost chunk is understood as a revision. Off the cuff, it might make more sense for the cli to default to rev 0 for devnets, but that's a bikeshedding conversation for another day. Thanks for fixing!
