### PR TITLE
Fix broken list-tx-hashes function for swap claims

### LINKED ISSUE #2547: `SwapClaim` transactions are not viewable by the view server
**Describe the bug**

`SwapClaim` transactions are not viewable by the view server:
```
~/c/p/penumbra (bsod-rename-unfilled|✔) $ cargo run --release --bin pcli -- -n http://localhost:8080 tx swap 1000test_usd --into penumbra
    Finished release [optimized] target(s) in 0.35s
     Running `target/release/pcli -n 'http://localhost:8080' tx swap 1000test_usd --into penumbra`
Scanning blocks from last sync height 48 to latest height 222
[0s] ██████████████████████████████████████████████████     174/174     4628/s ETA: 0s
building transaction...
finished proving in 0.980 seconds [2 actions, 1 proofs, 1169 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: fcd213335856605d149ba685953bcff86dbac7c2d616a7f988b0b1d6c489d6e4
Swap submitted and batch confirmed!
You will receive outputs of 0test_usd and 100penumbra. Claiming now...
building transaction...
finished proving in 0.001 seconds [1 actions, 0 proofs, 3179 bytes]
broadcasting transaction and awaiting confirmation...
transaction confirmed and detected: e80cfeef60ba0d1e6be7aefcb3b121eb9435508f1c3b8575769620d0e2c5f419
~/c/p/penumbra (bsod-rename-unfilled|✔) $ cargo run --release --bin pcli -- -n http://localhost:8080 view tx e80cfeef60ba0d1e6be7aefcb3b121eb9435508f1c3b8575769620d0e2c5f419
    Finished release [optimized] target(s) in 0.34s
     Running `target/release/pcli -n 'http://localhost:8080' view tx e80cfeef60ba0d1e6be7aefcb3b121eb9435508f1c3b8575769620d0e2c5f419`
Scanning blocks from last sync height 223 to latest height 227
[0s] ██████████████████████████████████████████████████       4/4       236/s ETA: 0s
Transaction not found in view service, fetching from fullnode...
 Action Type  Description
 Swap Claim   Opaque swap claim for trading pair: passet14h46dmcyy6fl5vyz7xx933n8l7jy202ahrxg92kad6yfladsvcyqczcwda <=> passet1984fctenw8m2fpl8a9wzguzp7j34d7vravryuhft808nyt9fdggqxmanqm with fee 0penumbra

 Transaction Fee                0penumbra
 Transaction Expiration Height  0
 ```

**Expected behavior**

There are at least two issues here:

1. The trading pair is unknown, meaning that the relevant denoms aren't being included in the TxP.  (Even if the swap claim were someone else's transaction, I should still be able to see the denoms of what pair it was claiming, that's public)
2. The transaction isn't viewable because it's not found in the view service. This could be because we're not flagging the transaction as one we should download?

### LINKED ISSUE #3214: Bug: `pcli view balance` not properly consolidating denoms
As shown here:

```
❯ pcli -n https://grpc.testnet-preview.penumbra.zone view balance
Scanning blocks from last sync height 976 to latest height 976
[0s] ██████████████████████████████████████████████████       0/0       0/s ETA: 0s
 Account  Amount          
 0        20000gm         
 0        501000test_usd  
 0        100cube         
 0        10000pizza      
 0        1002700penumbra 
 0        20000gn         
 0        8000test_usd    
 0        6300penumbra
```

Obviously this is suboptimal, could be a query issue. To be fixed.

### PR DESCRIPTION
**Pull request by aubrika**
View: removes code to skip storage of output notes of value 0, adds code to include transaction ids for incoming swaps to filtered blocks.

Closes #2547
Closes #3214

### CODE REVIEW

File: crates/view/src/storage.rs [hunk 1]
```diff
@@ -1169,11 +1169,6 @@ impl Storage {
     }
 
     pub async fn give_advice(&self, note: Note) -> anyhow::Result<()> {
-        // Do not insert advice for zero amounts, simply return Ok because this is fine
-        if u128::from(note.amount()) == 0u128 {
-            return Ok(());
-        }
```
Comment (redshiftzero) [inline crates/view/src/storage.rs:1175]: wow really nice find! Two thoughts:
1. I think we'd need to apply this same change in the view impl over in `IndexedDBStorage::store_advice` in the wasm crate, such that the same fix is applied over there
2. The implication of this change is that #2136 is re-introduced, so maybe we do something like filter out 0-valued notes when querying for spendable notes (then users won't see behavior like https://discord.com/channels/824484045370818580/915710988312002610/1087796172078469281). What do you think?

Comment (aubrika) [reply crates/view/src/storage.rs:1175]: Confirmed that this reintroduces the issue mentioned previously in discord:

```Scanning blocks from last sync height 156681 to latest height 160295
[0s] ██████████████████████████████████████████████████    3614/3614    4133/s ETA: 0s
 Account  Amount      
 0        1gm         
 0        0gm         
 0        9gm         
 0        0gm         
 0        0gm         
 0        996test_usd 
 0        1test_usd   
 0        5penumbra   
 0        4penumbra   
 0        0gn         
 0        0gn         
 0        7gn         
 0        1gn         
 0        1gn         
 0        1gn         
 0        30penumbra  
aubrey@penpro penumbra % 
```

I like your suggestion - the balances query needs fixing anyway (it's showing several rows for one denom instead of properly consolidating denoms, as in #3214 ), so it seems like not including zero-valued notes as "spendable" is something we always should have been doing. Good catch on also doing this in the wasm crate - I'll dig into this tomorrow, and if we're lucky this will also shed some light on the existing balances query issue. Thank you for the review!
